# Generated by Django 4.2.3 on 2023-07-17 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_no', models.CharField(blank=True, max_length=30, null=True)),
                ('Document_type', models.CharField(choices=[('ID', 'ID'), ('Certi', 'CERTIFICATE')], max_length=30)),
                ('Doc', models.ImageField(upload_to='documnet')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Document_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
