# Generated by Django 4.2.3 on 2023-07-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Document_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.document'),
        ),
    ]
