# Generated by Django 4.2.3 on 2023-07-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_document_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Document_no',
        ),
        migrations.AddField(
            model_name='document',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
