# Generated by Django 4.2.3 on 2023-07-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_student_document_no_document_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Document_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
