# Generated by Django 4.2.3 on 2023-07-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_document_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Phone',
        ),
    ]
